name: Spellcheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spellcheck with Hunspell
    run: |
    chmod +x spellcheck.sh
    ./spellcheck.sh